[build]
builder = "dockerfile"

[deploy]
startCommand = "python server.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
PORT = "8000"
